FROM bitnami/spark:latest
USER root
COPY requirements_pyspark.txt .
RUN pip install --no-cache-dir -r requirements_pyspark.txt
WORKDIR /app
COPY /scripts/Spark_traitement.py .
CMD ["spark-submit", \
     "--master", "spark://spark-master:7077", \
     "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0", \
     "Spark_traitement.py"]
